#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.

awk '{ status_count[$1" "$9]++ } END { for (key in status_count) print status_count[key], key }' apache-access.log | sort -nr
