#!/usr/bin/env bash
#Displays "Best School" 10 times using a while loop, but says "Hi" on the 9th iteration.

count=0

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
		((count++))
done
