#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20, but displays "bad luck from China" for the 4th loop iteration, "bad luck from Japan" bad luck from Japan and "bad luck from Italy"  for the 17th loop iteration

count=1

while [ $count -le 20 ]
do
	case $count in
		4)
			echo "$count"
			echo "bad luck from China"
			;;
		9)
			echo "$count"
			echo "bad luck from Japan"
			;;
		17)
			echo "$count"
			echo "bad luck from Italy"
			;;
		*)
			echo "$count"
			;;
	esac
	((count++))
done
