#!/usr/bin/env bash
#Displays the contents of the current directory in list format.

for file in *
do
	if [ -f "$file" ] && [ "${file:0:1}" != "." ]
	then
		filename=${file#*-}
		echo "$filename"
	fi
done
